name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install Depedency
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn

      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setting gloud
        run: |
          gcloud auth configure-docker
          gcloud container clusters get-credentials live01 --zone asia-northeast1-a --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Image
        run: |
          yarn build
          docker build . -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/life-game:latest
          docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/life-game:latest

      - name: Install Kubectl
        run: |
          curl -Lo kubectl "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install kubectl /usr/local/bin/

      - name: Deploy
        run: |
          kubectl rollout restart deployments/life-game
